# Generated by Django 3.1 on 2020-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CityServiceSubservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('subservice_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('pincode', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('pincode', models.IntegerField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservice_id', models.IntegerField()),
                ('expert_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('cust_id', models.IntegerField(default=-1)),
                ('expert_id', models.IntegerField(default=-1)),
                ('desc', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('service_id', models.IntegerField(default=-1)),
                ('subservice_id', models.IntegerField(default=-1)),
                ('expert_id', models.IntegerField(default=-1)),
                ('payment_id', models.IntegerField(default=-1)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city_id', models.IntegerField(default=-1)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(default='2020-12-31')),
                ('end_time', models.TimeField(default='11:59:00')),
                ('job_status', models.CharField(default='', max_length=20)),
                ('updated_by', models.IntegerField(default=-1)),
                ('updated_by_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_mode', models.CharField(default='', max_length=20)),
                ('job_id', models.IntegerField()),
                ('cust_id', models.IntegerField(default=-1)),
                ('expert_id', models.IntegerField(default=-1)),
                ('charges', models.IntegerField()),
                ('pay_status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('details', models.CharField(default='', max_length=200)),
                ('charges', models.IntegerField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('service_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='publication',
            field=models.CharField(default='', max_length=70),
        ),
    ]
